services:
  rstudio-server:
    build:
      context: .
      args:
        - R_PACKAGES=$R_PACKAGES
        - GH_PACKAGES=$GH_PACKAGES
    container_name: rss
    environment:
      - PASSWORD=${PASSWORD:?PASSWORD is required}
      - TZ=UTC
    ports:
      - 8787:8787
    volumes:
      - type: bind
        source: "${RSTUDIO_CONFIG_DIR:?RSTUDIO_CONFIG_DIR is required}"
        target: "/home/rstudio/.config"
      - type: bind
        source: "${CASES_DIR:?CASES_DIR is required}"
        target: "/home/rstudio/cases"
      - type: bind
        source: "${RSTUDIO_RSERVER_CONF:?RSTUDIO_RSERVER_CONF is required}"
        target: /etc/rstudio/rserver.conf
        read_only: true
    restart: always
