services:
  rstudio-server:
    build:
      context: .
      args:
        - R_PACKAGES_FILE=$R_PACKAGES_FILE
        - GH_PACKAGES_FILE=$GH_PACKAGES_FILE
    container_name: rss
    environment:
      - PASSWORD=${PASSWORD:?PASSWORD is required}
      - TZ=UTC
    ports:
      - 8787:8787
    volumes:
      - type: bind
        source: "${RSTUDIO_CONFIG_DIR:?RSTUDIO_CONFIG_DIR is required}"
        target: "/home/rstudio/.config"
      - type: bind
        source: "${CASES_DIR:?CASES_DIR is required}"
        target: "/home/rstudio/cases"
      - type: bind
        source: "${RSTUDIO_RSERVER_CONF:?RSTUDIO_RSERVER_CONF is required}"
        target: /etc/rstudio/rserver.conf
        read_only: true
      - type: bind
        source: "${CORP_CA_DIR:?CORP_CA_DIR is required}"
        target: /usr/local/share/ca-certificates/corp
        read_only: true
      - type: bind
        source: "${MSTICPY_CONFIG_FILE:?MSTICPY_CONFIG_FILE is required}"
        target: /home/rstudio/.msticpy/msticpyconfig.yaml
    restart: always
